services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "3030:3001" # Uptime Kuma web UI
    volumes:
      - ./uptime-kuma-data:/app/data
    environment:
      - TZ=Asia/thailand
