services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      JENKINS_OPTS: --httpListenAddress=0.0.0.0
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
