services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434" 
    volumes:
      - ollama_data:/root/.ollama
    # Optional: For GPU support (NVIDIA example)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Or specify a number
              capabilities: [gpu]
volumes:
  ollama_data:
